nameOverride: demo-app

config:
  secretStoreName: kubernetes-seed

image:
  repository: eso-config-demo
  tag: local
  pullPolicy: Never

service:
  port: 80
  targetPort: 8080

appsettings:
  Logging:
    LogLevel:
      Default: Information
  FeatureFlags:
    AllowAnonymousRegistration: false
    EnableHubspotEmails: true
    ClearAllSessionsOnSsoLogin: false
  Demo:
    EnvironmentName: shared-dev-default
    SecretSource: eso-kubernetes-provider
  Strapi:
    BaseUrl: https://strapi-cms.topstep.com/api/
  MarketDataApi:
    BaseUrl: http://webapi.marketdata.svc.cluster.local
    EventHubUrl: http://webapi.marketdata.svc.cluster.local/hubs/event
    BackAdjustHistoricalBars: true
  ElasticSearch:
    Url: https://elastic.local/
    Username: elastic
    CloudId: topstepx-demo:ZXMtdXM...==
  GatewayApi:
    UserActivityLogQueueName: activitylogs-demo
    AllowedApplications:
      FE29F223-1FD6-49FE-9FF1-AE03F219F90B:
        Name: Sim2Funded
      B76015F2-04D3-477E-9191-C5E22CB2C957:
        Name: Quantower
  Temporal:
    Address: topstepx-dev.tmprl.cloud:7233
    Namespace: topstepx-dev
    TaskQueues:
      - topstepx-temporal-worker-queue

secrets:
  refreshInterval: 5m
  store:
    remoteNamespace: eso-seed
    tokenSecretName: eso-kubernetes-store-token
    tokenSecretKey: token
  ConnectionStrings:
    Topstep:
      remoteKey: databases-postgres-demo
      database: dev
      includeErrorDetail: true
    TopstepReadOnly:
      remoteKey: databases-postgres-demo-readonly
      database: dev
      includeErrorDetail: true
    Chart:
      remoteKey: databases-chart-demo
      database: cqg-contract-bars
      commandTimeout: 900
  Jwt:
    remoteKey: auth-jwt-demo
    Secret: { property: secret }
  Temporal:
    remoteKey: temporal-demo
    ApiKey: { property: apiKey }
  MarketDataApi:
    remoteKey: api-marketdata-demo
    ApiKey: { property: apiKey }
  Strapi:
    remoteKey: api-strapi-demo
    Token: { property: token }
  Stripe:
    remoteKey: api-stripe-demo
    ApiKey: { property: apiKey }
  ElasticSearch:
    remoteKey: elasticsearch-demo
    Password: { property: password }
    CloudApiKey: { property: cloudApiKey }
  GatewayApi:
    remoteKey: gateway-api-demo
    AllowedApplications:
      FE29F223-1FD6-49FE-9FF1-AE03F219F90B:
        SecretKey: { property: sim2FundedSecretKey }
      B76015F2-04D3-477E-9191-C5E22CB2C957:
        SecretKey: { property: quantowerSecretKey }
