nameOverride: demo-app

config:
  secretStoreName: kubernetes-seed

image:
  repository: eso-config-demo
  tag: local
  pullPolicy: Never

service:
  port: 80
  targetPort: 8080

appsettings:
  Logging:
    LogLevel:
      Default: Information
  FeatureFlags:
    AllowAnonymousRegistration: false
    EnableHubspotEmails: true
    ClearAllSessionsOnSsoLogin: false
  Demo:
    EnvironmentName: shared-dev-default
    SecretSource: eso-kubernetes-provider
  Strapi:
    BaseUrl: https://strapi-cms.topstep.com/api/
  MarketDataApi:
    BaseUrl: http://webapi.marketdata.svc.cluster.local
    EventHubUrl: http://webapi.marketdata.svc.cluster.local/hubs/event
    BackAdjustHistoricalBars: true
  ElasticSearch:
    Url: https://elastic.local/
    Username: elastic
    CloudId: topstepx-demo:ZXMtdXM...==
  Temporal:
    Address: topstepx-dev.tmprl.cloud:7233
    Namespace: topstepx-dev
    TaskQueues:
      - topstepx-temporal-worker-queue

secrets:
  refreshInterval: 5m
  store:
    remoteNamespace: eso-seed
    tokenSecretName: eso-kubernetes-store-token
    tokenSecretKey: token
  template:
    ConnectionStrings:
      Topstep: "Username={{ .topstepUsername }};Password={{ .topstepPassword }};Host={{ .topstepHost }};Database=dev;Port={{ .topstepPort }};Include Error Detail=true"
      TopstepReadOnly: "Username={{ .topstepReadOnlyUsername }};Password={{ .topstepReadOnlyPassword }};Host={{ .topstepReadOnlyHost }};Database=dev;Port={{ .topstepReadOnlyPort }};Include Error Detail=true"
      Chart: "Username={{ .chartUsername }};Password={{ .chartPassword }};Host={{ .chartHost }};Database=cqg-contract-bars;Port={{ .chartPort }};Command Timeout=900"
    Jwt:
      Secret: "{{ .jwtSecret }}"
    Temporal:
      ApiKey: "{{ .temporalApiKey }}"
    MarketDataApi:
      ApiKey: "{{ .marketDataApiKey }}"
    Strapi:
      Token: "{{ .strapiToken }}"
    Stripe:
      ApiKey: "{{ .stripeApiKey }}"
    ElasticSearch:
      Password: "{{ .elasticSearchPassword }}"
      CloudApiKey: "{{ .elasticSearchCloudApiKey }}"
  vars:
    topstepHost:
      remoteKey: databases-postgres-demo
      property: host
    topstepPort:
      remoteKey: databases-postgres-demo
      property: port
    topstepUsername:
      remoteKey: databases-postgres-demo
      property: username
    topstepPassword:
      remoteKey: databases-postgres-demo
      property: password
    topstepReadOnlyHost:
      remoteKey: databases-postgres-demo-readonly
      property: host
    topstepReadOnlyPort:
      remoteKey: databases-postgres-demo-readonly
      property: port
    topstepReadOnlyUsername:
      remoteKey: databases-postgres-demo-readonly
      property: username
    topstepReadOnlyPassword:
      remoteKey: databases-postgres-demo-readonly
      property: password
    chartHost:
      remoteKey: databases-chart-demo
      property: host
    chartPort:
      remoteKey: databases-chart-demo
      property: port
    chartUsername:
      remoteKey: databases-chart-demo
      property: username
    chartPassword:
      remoteKey: databases-chart-demo
      property: password
    jwtSecret:
      remoteKey: auth-jwt-demo
      property: secret
    temporalApiKey:
      remoteKey: temporal-demo
      property: apiKey
    marketDataApiKey:
      remoteKey: api-marketdata-demo
      property: apiKey
    strapiToken:
      remoteKey: api-strapi-demo
      property: token
    stripeApiKey:
      remoteKey: api-stripe-demo
      property: apiKey
    elasticSearchPassword:
      remoteKey: elasticsearch-demo
      property: password
    elasticSearchCloudApiKey:
      remoteKey: elasticsearch-demo
      property: cloudApiKey
