topstepx:
  nameOverride: demo-app

  config:
    secretStoreName: kubernetes-seed

  image:
    repository: eso-config-demo
    tag: local
    pullPolicy: Never

  appsettings:
    Demo:
      EnvironmentName: demo
 
  secrets:
    refreshInterval: 1m
    store:
      remoteNamespace: eso-seed
      tokenSecretName: eso-kubernetes-store-token
      tokenSecretKey: token
    sources:
      topstep:
        remoteKey: databases-postgres-demo
      topstepReadOnly:
        remoteKey: databases-postgres-demo-readonly
      chart:
        remoteKey: databases-chart-demo
      jwt:
        remoteKey: auth-jwt-demo
      temporal:
        remoteKey: temporal-demo
      marketDataApi:
        remoteKey: api-marketdata-demo
      strapi:
        remoteKey: api-strapi-demo
      stripe:
        remoteKey: api-stripe-demo
    bindings:
      ConnectionStrings:
        Topstep:
          database: demo
        TopstepReadOnly:
          database: demo
        Chart:
          database: cqg-contract-bars-demo
      Jwt:
        Secret:
          source: jwt
          property: secret
      Temporal:
        ApiKey:
          source: temporal
          property: apiKey
      MarketDataApi:
        ApiKey:
          source: marketDataApi
          property: apiKey
      Strapi:
        Token:
          source: strapi
          property: token
      Stripe:
        ApiKey:
          source: stripe
          property: apiKey
