apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: appsettings-secrets
  labels:
    {{- include "topstepx.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.config.secretStoreName }}
    kind: SecretStore
  target:
    name: appsettings-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        appsettings.secrets.json: |-
          {
            "ConnectionStrings": {
              "Topstep": "Username={{ `{{ .topstepUsername }}` }};Password={{ `{{ .topstepPassword }}` }};Host={{ `{{ .topstepHost }}` }};Database={{ required "secrets.ConnectionStrings.Topstep.database is required" .Values.secrets.ConnectionStrings.Topstep.database }};Port={{ `{{ .topstepPort }}` }}{{- if .Values.secrets.ConnectionStrings.Topstep.includeErrorDetail }};Include Error Detail=true{{- end }}{{- with .Values.secrets.ConnectionStrings.Topstep.commandTimeout }};Command Timeout={{ . }}{{- end }}",
              "TopstepReadOnly": "Username={{ `{{ .topstepReadOnlyUsername }}` }};Password={{ `{{ .topstepReadOnlyPassword }}` }};Host={{ `{{ .topstepReadOnlyHost }}` }};Database={{ required "secrets.ConnectionStrings.TopstepReadOnly.database is required" .Values.secrets.ConnectionStrings.TopstepReadOnly.database }};Port={{ `{{ .topstepReadOnlyPort }}` }}{{- if .Values.secrets.ConnectionStrings.TopstepReadOnly.includeErrorDetail }};Include Error Detail=true{{- end }}{{- with .Values.secrets.ConnectionStrings.TopstepReadOnly.commandTimeout }};Command Timeout={{ . }}{{- end }}",
              "Chart": "Username={{ `{{ .chartUsername }}` }};Password={{ `{{ .chartPassword }}` }};Host={{ `{{ .chartHost }}` }};Database={{ required "secrets.ConnectionStrings.Chart.database is required" .Values.secrets.ConnectionStrings.Chart.database }};Port={{ `{{ .chartPort }}` }}{{- if .Values.secrets.ConnectionStrings.Chart.includeErrorDetail }};Include Error Detail=true{{- end }}{{- with .Values.secrets.ConnectionStrings.Chart.commandTimeout }};Command Timeout={{ . }}{{- end }}"
            },
            "Jwt": {
              "Secret": "{{ `{{ .jwtSecret }}` }}"
            },
            "Temporal": {
              "ApiKey": "{{ `{{ .temporalApiKey }}` }}"
            },
            "MarketDataApi": {
              "ApiKey": "{{ `{{ .marketDataApiKey }}` }}"
            },
            "Strapi": {
              "Token": "{{ `{{ .strapiToken }}` }}"
            },
            "Stripe": {
              "ApiKey": "{{ `{{ .stripeApiKey }}` }}"
            },
            "ElasticSearch": {
              "Password": "{{ `{{ .elasticSearchPassword }}` }}",
              "CloudApiKey": "{{ `{{ .elasticSearchCloudApiKey }}` }}"
            }
          }
  data:
    - secretKey: topstepHost
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Topstep.remoteKey is required" .Values.secrets.ConnectionStrings.Topstep.remoteKey | quote }}
        property: host
    - secretKey: topstepPort
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Topstep.remoteKey is required" .Values.secrets.ConnectionStrings.Topstep.remoteKey | quote }}
        property: port
    - secretKey: topstepUsername
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Topstep.remoteKey is required" .Values.secrets.ConnectionStrings.Topstep.remoteKey | quote }}
        property: username
    - secretKey: topstepPassword
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Topstep.remoteKey is required" .Values.secrets.ConnectionStrings.Topstep.remoteKey | quote }}
        property: password
    - secretKey: topstepReadOnlyHost
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.TopstepReadOnly.remoteKey is required" .Values.secrets.ConnectionStrings.TopstepReadOnly.remoteKey | quote }}
        property: host
    - secretKey: topstepReadOnlyPort
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.TopstepReadOnly.remoteKey is required" .Values.secrets.ConnectionStrings.TopstepReadOnly.remoteKey | quote }}
        property: port
    - secretKey: topstepReadOnlyUsername
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.TopstepReadOnly.remoteKey is required" .Values.secrets.ConnectionStrings.TopstepReadOnly.remoteKey | quote }}
        property: username
    - secretKey: topstepReadOnlyPassword
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.TopstepReadOnly.remoteKey is required" .Values.secrets.ConnectionStrings.TopstepReadOnly.remoteKey | quote }}
        property: password
    - secretKey: chartHost
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Chart.remoteKey is required" .Values.secrets.ConnectionStrings.Chart.remoteKey | quote }}
        property: host
    - secretKey: chartPort
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Chart.remoteKey is required" .Values.secrets.ConnectionStrings.Chart.remoteKey | quote }}
        property: port
    - secretKey: chartUsername
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Chart.remoteKey is required" .Values.secrets.ConnectionStrings.Chart.remoteKey | quote }}
        property: username
    - secretKey: chartPassword
      remoteRef:
        key: {{ required "secrets.ConnectionStrings.Chart.remoteKey is required" .Values.secrets.ConnectionStrings.Chart.remoteKey | quote }}
        property: password
    - secretKey: jwtSecret
      remoteRef:
        key: {{ required "secrets.Jwt.remoteKey is required" .Values.secrets.Jwt.remoteKey | quote }}
        property: {{ default "secret" .Values.secrets.Jwt.Secret.property }}
    - secretKey: temporalApiKey
      remoteRef:
        key: {{ required "secrets.Temporal.remoteKey is required" .Values.secrets.Temporal.remoteKey | quote }}
        property: {{ default "apiKey" .Values.secrets.Temporal.ApiKey.property }}
    - secretKey: marketDataApiKey
      remoteRef:
        key: {{ required "secrets.MarketDataApi.remoteKey is required" .Values.secrets.MarketDataApi.remoteKey | quote }}
        property: {{ default "apiKey" .Values.secrets.MarketDataApi.ApiKey.property }}
    - secretKey: strapiToken
      remoteRef:
        key: {{ required "secrets.Strapi.remoteKey is required" .Values.secrets.Strapi.remoteKey | quote }}
        property: {{ default "token" .Values.secrets.Strapi.Token.property }}
    - secretKey: stripeApiKey
      remoteRef:
        key: {{ required "secrets.Stripe.remoteKey is required" .Values.secrets.Stripe.remoteKey | quote }}
        property: {{ default "apiKey" .Values.secrets.Stripe.ApiKey.property }}
    - secretKey: elasticSearchPassword
      remoteRef:
        key: {{ required "secrets.ElasticSearch.remoteKey is required" .Values.secrets.ElasticSearch.remoteKey | quote }}
        property: {{ default "password" .Values.secrets.ElasticSearch.Password.property }}
    - secretKey: elasticSearchCloudApiKey
      remoteRef:
        key: {{ required "secrets.ElasticSearch.remoteKey is required" .Values.secrets.ElasticSearch.remoteKey | quote }}
        property: {{ default "cloudApiKey" .Values.secrets.ElasticSearch.CloudApiKey.property }}
