topstepx:
  nameOverride: demo-app

  config:
    secretStoreName: kubernetes-seed
    secretsEnv: demo-override

  image:
    repository: eso-config-demo
    tag: local
    pullPolicy: Never

  appsettings:
    FeatureFlags:
      EnableHubspotEmails: false
    Demo:
      EnvironmentName: demo-override
    HedgeDetection:
      ImmediateEnforcementThreshold: 12
    Temporal:
      Namespace: topstepx-dev-override

  secrets:
    ConnectionStrings:
      Topstep:
        database: demo_override
      TopstepReadOnly:
        database: demo_override
      Chart:
        database: cqg-contract-bars-demo-override
