topstepx:
  nameOverride: demo-app

  config:
    secretStoreName: kubernetes-seed

  image:
    repository: eso-config-demo
    tag: local
    pullPolicy: Never

  appsettings:
    FeatureFlags:
      EnableHubspotEmails: false
    Demo:
      EnvironmentName: demo-override
    HedgeDetection:
      ImmediateEnforcementThreshold: 12
    Temporal:
      Namespace: topstepx-dev-override

  secrets:
    refreshInterval: 1m
    store:
      remoteNamespace: eso-seed
      tokenSecretName: eso-kubernetes-store-token
      tokenSecretKey: token
    ConnectionStrings:
      Topstep:
        remoteKey: databases-postgres-demo-override
        database: demo_override
      TopstepReadOnly:
        remoteKey: databases-postgres-demo-override-readonly
        database: demo_override
      Chart:
        remoteKey: databases-chart-demo-override
        database: cqg-contract-bars-demo-override
    Jwt:
      remoteKey: auth-jwt-demo-override
      Secret: { property: secret }
    Temporal:
      remoteKey: temporal-demo-override
      ApiKey: { property: apiKey }
    MarketDataApi:
      remoteKey: api-marketdata-demo-override
      ApiKey: { property: apiKey }
    Strapi:
      remoteKey: api-strapi-demo-override
      Token: { property: token }
    Stripe:
      remoteKey: api-stripe-demo-override
      ApiKey: { property: apiKey }
    ElasticSearch:
      remoteKey: elasticsearch-demo-override
