topstepx:
  nameOverride: demo-app

  config:
    secretStoreName: kubernetes-seed

  image:
    repository: eso-config-demo
    tag: local
    pullPolicy: Never

  appsettings:
    FeatureFlags:
      EnableHubspotEmails: false
    Demo:
      EnvironmentName: demo-override
    HedgeDetection:
      ImmediateEnforcementThreshold: 12
    Temporal:
      Namespace: topstepx-dev-override

  secrets:
    refreshInterval: 1m
    store:
      remoteNamespace: eso-seed
      tokenSecretName: eso-kubernetes-store-token
      tokenSecretKey: token
    template:
      ConnectionStrings:
        Topstep: "Username={{ .topstepUsername }};Password={{ .topstepPassword }};Host={{ .topstepHost }};Database=demo_override;Port={{ .topstepPort }};Include Error Detail=true"
        TopstepReadOnly: "Username={{ .topstepReadOnlyUsername }};Password={{ .topstepReadOnlyPassword }};Host={{ .topstepReadOnlyHost }};Database=demo_override;Port={{ .topstepReadOnlyPort }};Include Error Detail=true"
        Chart: "Username={{ .chartUsername }};Password={{ .chartPassword }};Host={{ .chartHost }};Database=cqg-contract-bars-demo-override;Port={{ .chartPort }};Command Timeout=900"
    vars:
      topstepHost:
        remoteKey: databases-postgres-demo-override
      topstepPort:
        remoteKey: databases-postgres-demo-override
      topstepUsername:
        remoteKey: databases-postgres-demo-override
      topstepPassword:
        remoteKey: databases-postgres-demo-override
      topstepReadOnlyHost:
        remoteKey: databases-postgres-demo-override-readonly
      topstepReadOnlyPort:
        remoteKey: databases-postgres-demo-override-readonly
      topstepReadOnlyUsername:
        remoteKey: databases-postgres-demo-override-readonly
      topstepReadOnlyPassword:
        remoteKey: databases-postgres-demo-override-readonly
      chartHost:
        remoteKey: databases-chart-demo-override
      chartPort:
        remoteKey: databases-chart-demo-override
      chartUsername:
        remoteKey: databases-chart-demo-override
      chartPassword:
        remoteKey: databases-chart-demo-override
      jwtSecret:
        remoteKey: auth-jwt-demo-override
      temporalApiKey:
        remoteKey: temporal-demo-override
      marketDataApiKey:
        remoteKey: api-marketdata-demo-override
      strapiToken:
        remoteKey: api-strapi-demo-override
      stripeApiKey:
        remoteKey: api-stripe-demo-override
      elasticSearchPassword:
        remoteKey: elasticsearch-demo-override
      elasticSearchCloudApiKey:
        remoteKey: elasticsearch-demo-override
