apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-override
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: main
    path: envs/demo-override
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-override
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
